export enum InjectionToken {
  WALLET_REPOSITORY = 'WALLET_REPOSITORY',
  ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  HISTORY_REPOSITORY = 'HISTORY_REPOSITORY',
  AUTHENTICATOR = 'AUTHENTICATOR',
}
